import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'es' | 'it' | 'de' | 'nl' | 'pt' | 'sv';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // App
    'app.title': 'TimeXP',
    'app.subtitle': 'Skill Development Tracker',
    'app.greeting.morning': 'Good morning',
    'app.greeting.afternoon': 'Good afternoon',
    'app.greeting.evening': 'Good evening',
    'app.motivation.1': 'What are we working on today?',
    'app.motivation.2': 'Ready to make progress?',
    'app.motivation.3': 'Time to achieve your goals!',
    'app.motivation.4': 'Let\'s build something amazing!',
    'app.motivation.5': 'Your next breakthrough awaits!',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.pinned': 'Pinned',
    'nav.categories': 'Categories',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.profile': 'Profile',
    
    // Dashboard
    'dashboard.totalTime': 'Total Time Logged',
    'dashboard.activeProjects': 'Active Projects',
    'dashboard.tasksCompleted': 'Tasks Completed',
    'dashboard.newCategory': 'New Category',
    'dashboard.noCategories': 'No categories created yet',
    'dashboard.createFirstCategory': 'Create your first category',
    
    // Skills
    'projects.new': 'New Skill',
    'projects.pinned': 'Pinned Skills',
    'projects.noPinned': 'No pinned skills yet',
    'projects.noProjects': 'No skills created yet',
    'projects.createFirst': 'Create your first skill',
    'projects.totalTime': 'Total Time',
    'projects.tasks': 'Tasks',
    'projects.more': 'more skills',
    'projects.noSkillsInCategory': 'No skills in this category',
    'projects.archive': 'Archive',
    'projects.unarchive': 'Unarchive',
    'projects.archived': 'Archived',
    'projects.showArchived': 'Show Archived',
    'projects.hideArchived': 'Hide Archived',
    'projects.noArchived': 'No archived skills',
    
    // Timer
    'timer.start': 'Start',
    'timer.pause': 'Pause',
    'timer.resume': 'Resume',
    'timer.stop': 'Stop',
    'timer.currentSession': 'Current session',
    'timer.addSession': 'Add Session',
    'timer.addManualSession': 'Add Manual Session',
    'timer.focusTime': 'Focus Time',
    'timer.breakTime': 'Break Time',
    'timer.totalDuration': 'Total Duration',
    'timer.startTime': 'Start Time',
    'timer.description': 'Description',
    'timer.descriptionPlaceholder': 'What did you work on during this session?',
    'timer.hours': 'Hours',
    'timer.minutes': 'Minutes',
    'timer.date': 'Date',
    
    // Tasks
    'tasks.title': 'Tasks',
    'tasks.add': 'Add',
    'tasks.addTask': 'Add Task',
    'tasks.noTasks': 'No tasks created yet. Add your first task to get started!',
    'tasks.deadline': 'Deadline (optional)',
    'tasks.priority': 'Priority',
    'tasks.priority.low': 'Low',
    'tasks.priority.medium': 'Medium',
    'tasks.priority.high': 'High',
    'tasks.dueToday': 'Due today',
    'tasks.dueTomorrow': 'Due tomorrow',
    'tasks.dueInDays': 'Due in {days} days',
    'tasks.overdue': '{days} days overdue',
    'tasks.taskName': 'Task name...',
    'tasks.lowPriority': 'low priority',
    'tasks.mediumPriority': 'medium priority',
    'tasks.highPriority': 'high priority',
    
    // Notes
    'notes.title': 'Notes',
    'notes.add': 'Add Note',
    'notes.addNote': 'Add Note',
    'notes.newNote': 'New Note',
    
    // Categories
    'categories.discoverCategories': 'Discover Categories',
    'categories.trendingSkills': 'Trending Skills',
    'categories.trending': 'Trending',
    'categories.adopt': 'Adopt',
    'categories.adoptCategory': 'Adopt Category',
    'categories.skills': 'skills',
    'categories.skillsIncluded': 'Skills included',
    
    // Skills
    'skills.difficulty.beginner': 'Beginner',
    'skills.difficulty.intermediate': 'Intermediate',
    'skills.difficulty.advanced': 'Advanced',
    'skills.difficulty.expert': 'Expert',
    'notes.saveNote': 'Save Note',
    'notes.noNotes': 'No notes yet. Add your first note to keep track of important information!',
    'notes.edit': 'Edit',
    'notes.preview': 'Preview',
    'notes.placeholder': 'Write your note using markdown...',
    'notes.createFirst': 'Create your first note',
    
    // Sessions
    'sessions.title': 'Recent Sessions',
    'sessions.noSessions': 'No sessions recorded yet',
    'sessions.pomodoro': 'Pomodoro',
    'sessions.break': 'Break',
    
    // Achievements
    'achievements.title': 'Réalisations',
    'achievements.level': 'Niveau de Réalisation',
    'achievements.nextGoal': 'Prochain Objectif : {hours}h',
    'achievements.remaining': '{hours}h restantes ({percent}% terminé)',
    'achievements.maxLevel': '🎉 Niveau Maximum Atteint !',
    'achievements.maxLevelDesc': 'Vous avez atteint le niveau de réalisation le plus élevé',
    'achievements.levels.starter': 'Débutant',
    'achievements.levels.beginner': 'Novice',
    'achievements.levels.intermediate': 'Intermédiaire',
    'achievements.levels.advanced': 'Avancé',
    'achievements.levels.expert': 'Expert',
    'achievements.levels.master': 'Maître',
    'achievements.unlocked': 'débloqué',
    'achievements.totalTime': 'Temps Total',
    'achievements.tasksDone': 'Tâches Terminées',
    'achievements.next': 'Suivant',
    'achievements.progress': 'Progression',
    'achievements.yourAchievements': 'Vos Réalisations',
    'achievements.gettingStarted': 'Premiers Pas',
    'achievements.gettingStartedDesc': 'Enregistrez votre première heure',
    'achievements.dedicatedLearner': 'Apprenant Dévoué',
    'achievements.dedicatedLearnerDesc': 'Atteignez 10 heures au total',
    'achievements.skillBuilder': 'Bâtisseur de Compétences',
    'achievements.skillBuilderDesc': 'Atteignez 100 heures',
    'achievements.taskMaster': 'Maître des Tâches',
    'achievements.taskMasterDesc': 'Complétez 50 tâches',
    'achievements.pomodoroPro': 'Pro du Pomodoro',
    'achievements.pomodoroProDesc': 'Complétez 25 sessions pomodoro',
    'achievements.consistencyKing': 'Roi de la Constance',
    'achievements.consistencyKingDesc': 'Enregistrez 100 sessions',
    
    // Profile
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your account and view achievements',
    'profile.personalInfo': 'Personal Information',
    'profile.fullName': 'Full Name',
    'profile.nickname': 'Nickname',
    'profile.dateOfBirth': 'Date of Birth',
    'profile.security': 'Security',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm New Password',
    'profile.changePassword': 'Change Password',
    'profile.soundNotifications': 'Sound Notifications',
    'profile.soundDesc': 'Play sounds for achievements and timers',
    'profile.exportData': 'Export All Data',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile & Achievements',
    'settings.security': 'Security',
    'settings.audio': 'Audio',
    'settings.notifications': 'Notifications',
    'settings.data': 'Data',
    'settings.personalInfo': 'Personal Information',
    'settings.fullName': 'Full Name',
    'settings.nickname': 'Nickname',
    'settings.dateOfBirth': 'Date of Birth',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm New Password',
    'settings.changePassword': 'Change Password',
    'settings.soundNotifications': 'Sound Notifications',
    'settings.soundDesc': 'Play sounds for achievements, pomodoro, and task completion',
    'settings.monthlyReports': 'Monthly Progress Reports',
    'settings.monthlyReportsDesc': 'Get monthly summaries of your progress',
    'settings.weeklyReminders': 'Weekly Goal Reminders',
    'settings.weeklyRemindersDesc': 'Get weekly reminders about your goals',
    'settings.exportData': 'Export All Data',
    'settings.resetData': 'Reset All Data',
    'settings.saveSettings': 'Save Settings',
    'settings.danger': 'Danger Zone',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountWarning': 'This action will permanently delete your account and all associated data. This action cannot be undone.',
    'settings.deleteAccountConfirm': 'Are you absolutely sure? This action cannot be undone.',
    'settings.confirmDelete': 'Yes, Delete My Account',
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme',
    'settings.themeDesc': 'Switch between light and dark mode',
    'settings.language': 'Language',
    'settings.languageDesc': 'Choose your preferred language for the application',
    'settings.onboarding': 'Onboarding',
    'settings.onboardingTitle': 'Complete Your Profile Setup',
    'settings.onboardingDesc': 'Set up your interests, language preferences, and daily goals to personalize your experience.',
    'settings.startOnboarding': 'Start Onboarding',
    
    // Guide
    'guide.welcome': 'Welcome to TimeXP!',
    'guide.letsGetStarted': 'Let\'s get you started with your productivity journey',
    'guide.step': 'Step',
    'guide.whatIsTimeXP': 'What is TimeXP?',
    'guide.timeXPDescription': 'TimeXP is your personal time tracking and productivity companion. Track your time, organize your projects, and grow your skills.',
    'guide.trackTime': 'Track Time',
    'guide.trackTimeDesc': 'Monitor how you spend your time on different activities',
    'guide.organize': 'Organize',
    'guide.organizeDesc': 'Keep your projects and tasks organized by categories',
    'guide.grow': 'Grow',
    'guide.growDesc': 'Build better habits and improve your productivity',
    'guide.setupCategories': 'Setup Your Categories',
    'guide.categoriesDescription': 'Based on your interests, we\'ll create categories to organize your projects.',
    'guide.yourInterests': 'Your Interests',
    'guide.createCategoriesFromInterests': 'Create Categories from Interests',
    'guide.addSkills': 'Add Your Skills',
    'guide.skillsDescription': 'Add specific skills within your categories to track your progress.',
    'guide.addFirstSkill': 'Add Your First Skill',
    'guide.skipForNow': 'Skip for now',
    'guide.skillName': 'Skill Name',
    'guide.skillNamePlaceholder': 'e.g., React, Photoshop, Piano',
    'guide.addSkill': 'Add Skill',
    'guide.readyToGo': 'You\'re Ready to Go!',
    'guide.readyDescription': 'Your TimeXP workspace is set up and ready for your productivity journey.',
    'guide.readyCheck1': 'Your profile is configured',
    'guide.readyCheck2': 'Categories are created from your interests',
    'guide.readyCheck3': 'You can start tracking your time',
    'guide.startUsing': 'Start Using TimeXP',
    
    // Playlists
    'playlist.title': 'Playlist',
    'playlist.add': 'Add Playlist',
    'playlist.url': 'Playlist URL',
    'playlist.urlPlaceholder': 'Enter Spotify, YouTube, or Apple Music playlist URL',
    'playlist.name': 'Playlist Name',
    'playlist.namePlaceholder': 'Enter a name for this playlist',
    'playlist.save': 'Save Playlist',
    'playlist.remove': 'Remove Playlist',
    'playlist.noPlaylist': 'No playlist added yet',
    'playlist.addFirst': 'Add a playlist to listen while working',
    
    // Categories
    'categories.name': 'Category Name',
    'categories.namePlaceholder': 'e.g. Development, Design, Personal...',
    'categories.color': 'Color',
    'categories.icon': 'Icon',
    'categories.create': 'Create Category',
    
    // Projects
    'project.name': 'Project Name',
    'project.namePlaceholder': 'e.g. Client Website, Mobile App...',
    'project.category': 'Category',
    'project.description': 'Description (optional)',
    'project.descriptionPlaceholder': 'Briefly describe this project...',
    'project.create': 'Create Project',
    'project.enablePomodoro': 'Enable Pomodoro Technique',
    'project.focusTimeMinutes': 'Focus Time (minutes)',
    'project.breakTimeMinutes': 'Break Time (minutes)',
    
    // Pomodoro
    'pomodoro.title': 'Pomodoro Stats',
    'pomodoro.completedSessions': 'Completed Sessions',
    'pomodoro.focusTime': 'Focus Time',
    'pomodoro.breakTime': 'Break Time',
    'pomodoro.mode': 'Pomodoro Mode',
    
    // Toast
    'toast.hide': 'Hide Timer',
    'toast.show': 'Show Timer',
    'toast.minimize': 'Minimize',
    'toast.expand': 'Expand',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.create': 'Create',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.online': 'Online',
    'common.light': 'Light',
    'common.dark': 'Dark',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    
    // Authentication
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInToContinue': 'Sign in to continue to TimeXP',
    'auth.createAccount': 'Create Account',
    'auth.signUpToGetStarted': 'Sign up to get started with TimeXP',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.noAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.checkYourEmail': 'Check Your Email',
    'auth.verificationEmailSent': 'We sent a verification email to your inbox',
    'auth.resetPasswordEmailSent': 'We sent a password reset link to your email',
    'auth.backToSignIn': 'Back to Sign In',
    'auth.enterEmailToReset': 'Enter your email to reset your password',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.passwordsDoNotMatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 6 characters long',
    'auth.chooseNickname': 'Choose your nickname to get started',
    'auth.nickname': 'Nickname',
    'auth.nicknamePlaceholder': 'Enter your nickname',
    'auth.continue': 'Continue',
    
    // Upcoming Tasks
    'upcomingTasks.title': 'Upcoming Tasks',
    'upcomingTasks.noDeadlines': 'No upcoming deadlines',
    'upcomingTasks.addDeadlines': 'Add deadlines to your tasks to see them here',
    'upcomingTasks.showingNext': 'Showing next 5 tasks',
    
    // Onboarding
    'onboarding.welcome': 'Welcome to TimeXP!',
    'onboarding.setupProfile': 'Let\'s set up your profile to personalize your experience',
    'onboarding.step': 'Step',
    'onboarding.nickname': 'What should we call you?',
    'onboarding.nicknamePlaceholder': 'Enter your nickname',
    'onboarding.nicknameHelp': 'This is how you\'ll appear in the app',
    'onboarding.interests': 'What are your interests?',
    'onboarding.interestsHelp': 'Select your main areas of interest to customize your experience',
    'onboarding.interests.programming': 'Programming',
    'onboarding.interests.design': 'Design',
    'onboarding.interests.music': 'Music',
    'onboarding.interests.gaming': 'Gaming',
    'onboarding.interests.photography': 'Photography',
    'onboarding.interests.cooking': 'Cooking',
    'onboarding.interests.travel': 'Travel',
    'onboarding.interests.reading': 'Reading',
    'onboarding.preferredLanguage': 'What\'s your preferred language?',
    'onboarding.dailyGoal': 'Daily Goal (hours)',
    'onboarding.dailyGoalHelp': 'How many hours do you want to work on your skills each day?',
    'onboarding.complete': 'Complete Setup',
    
    // Admin
    'admin.skills.title': 'Skills Management',
    'admin.skills.subtitle': 'Manage available skills and track their popularity',
    'admin.skills.addSkill': 'Add Skill',
    'admin.skills.editSkill': 'Edit Skill',
    'admin.skills.totalSkills': 'Total Skills',
    'admin.skills.activeSkills': 'Active Skills',
    'admin.skills.totalUsers': 'Total Users',
    'admin.skills.skill': 'Skill',
    'admin.skills.category': 'Category',
    'admin.skills.popularity': 'Popularity',
    'admin.skills.status': 'Status',
    'admin.skills.actions': 'Actions',
    'admin.skills.active': 'Active',
    'admin.skills.inactive': 'Inactive',
    'admin.skills.name': 'Name',
    'admin.skills.description': 'Description',
    'admin.skills.color': 'Color',
    'admin.skills.categories.programming': 'Programming',
    'admin.skills.categories.design': 'Design',
    'admin.skills.categories.music': 'Music',
    'admin.skills.categories.gaming': 'Gaming',
    'admin.skills.categories.photography': 'Photography',
    'admin.skills.categories.cooking': 'Cooking',
    'admin.skills.categories.travel': 'Travel',
    'admin.skills.categories.reading': 'Reading',
    'admin.skills.categories.fitness': 'Fitness',
    'admin.skills.categories.art': 'Art',
    'admin.skills.categories.business': 'Business',
    'admin.skills.categories.education': 'Education',
    
    // Admin Panel - New Features
    'admin.overview': 'Overview',
    'admin.categories': 'Categories',
    'admin.users': 'Users',
    'admin.articles': 'Articles',
    'admin.analytics': 'Analytics',
    'admin.recentUsers': 'Recent Users',
    'admin.trendingSkills': 'Trending Skills',
    'admin.defaultCategories': 'Default Categories Management',
    'admin.manageDefaultCategories': 'Manage default categories and their skills',
    'admin.userManagement': 'User Management',
    'admin.manageUsers': 'Manage users and their access',
    'admin.articleManagement': 'Article Management',
    'admin.createManageArticles': 'Create and manage articles for users',
    'admin.createArticle': 'Create Article',
    'admin.advancedAnalytics': 'Advanced Analytics',
    'admin.userGrowth': 'User Growth',
    'admin.skillPopularity': 'Skill Popularity',
    'admin.timeTrackingAnalytics': 'Time Tracking Analytics',
    'admin.totalHoursTracked': 'Total Hours Tracked',
    'admin.averageSessionLength': 'Average Session Length',
    'admin.categoryDistribution': 'Category Distribution',
    'admin.chartComingSoon': 'Chart coming soon...',
    'admin.loadingAdminData': 'Loading admin data...',
    'admin.noNickname': 'No nickname',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.joined': 'Joined',
    'admin.actions': 'Actions',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.trending': 'Trending',
    'admin.skills': 'skills',
    'admin.hours': 'hours',
    'admin.minutes': 'minutes'
  },
  fr: {
    // App
    'app.title': 'TimeXP',
    'app.subtitle': 'Suivi du Développement des Compétences',
    'app.greeting.morning': 'Bonjour',
    'app.greeting.afternoon': 'Bon après-midi',
    'app.greeting.evening': 'Bonsoir',
    'app.motivation.1': 'Sur quoi travaillons-nous aujourd\'hui ?',
    'app.motivation.2': 'Prêt à progresser ?',
    'app.motivation.3': 'Il est temps d\'atteindre vos objectifs !',
    'app.motivation.4': 'Construisons quelque chose d\'incroyable !',
    'app.motivation.5': 'Votre prochaine percée vous attend !',
    
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.pinned': 'Épinglés',
    'nav.categories': 'Catégories',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Déconnexion',
    'nav.login': 'Connexion',
    'nav.profile': 'Profil',
    
    // Dashboard
    'dashboard.totalTime': 'Temps Total Enregistré',
    'dashboard.activeProjects': 'Compétences Actives',
    'dashboard.tasksCompleted': 'Tâches Terminées',
    'dashboard.newCategory': 'Nouvelle Catégorie',
    'dashboard.noCategories': 'Aucune catégorie créée',
    'dashboard.createFirstCategory': 'Créez votre première catégorie',
    
    // Skills
    'projects.new': 'Nouvelle Compétence',
    'projects.pinned': 'Compétences Épinglées',
    'projects.noPinned': 'Aucune compétence épinglée',
    'projects.noProjects': 'Aucune compétence créée',
    'projects.createFirst': 'Créez votre première compétence',
    'projects.totalTime': 'Temps Total',
    'projects.tasks': 'Tâches',
    'projects.more': 'compétences supplémentaires',
    'projects.noSkillsInCategory': 'Aucune compétence présente dans cette catégorie',
    'projects.archive': 'Archiver',
    'projects.unarchive': 'Désarchiver',
    'projects.archived': 'Archivées',
    'projects.showArchived': 'Afficher les archivées',
    'projects.hideArchived': 'Masquer les archivées',
    'projects.noArchived': 'Aucune compétence archivée',
    
    // Timer
    'timer.start': 'Start',
    'timer.pause': 'Pause',
    'timer.resume': 'Resume',
    'timer.stop': 'Stop',
    'timer.currentSession': 'Current session',
    'timer.addSession': 'Add Session',
    'timer.addManualSession': 'Add Manual Session',
    'timer.focusTime': 'Focus Time',
    'timer.breakTime': 'Break Time',
    'timer.totalDuration': 'Total Duration',
    'timer.startTime': 'Start Time',
    'timer.description': 'Description',
    'timer.descriptionPlaceholder': 'What did you work on during this session?',
    'timer.hours': 'Hours',
    'timer.minutes': 'Minutes',
    'timer.date': 'Date',
    
    // Tasks
    'tasks.title': 'Tasks',
    'tasks.add': 'Add',
    'tasks.addTask': 'Add Task',
    'tasks.noTasks': 'No tasks created yet. Add your first task to get started!',
    'tasks.deadline': 'Deadline (optional)',
    'tasks.priority': 'Priority',
    'tasks.priority.low': 'Low',
    'tasks.priority.medium': 'Medium',
    'tasks.priority.high': 'High',
    'tasks.dueToday': 'Due today',
    'tasks.dueTomorrow': 'Due tomorrow',
    'tasks.dueInDays': 'Due in {days} days',
    'tasks.overdue': '{days} days overdue',
    'tasks.taskName': 'Task name...',
    'tasks.lowPriority': 'low priority',
    'tasks.mediumPriority': 'medium priority',
    'tasks.highPriority': 'high priority',
    
    // Notes
    'notes.title': 'Notes',
    'notes.add': 'Add Note',
    'notes.addNote': 'Add Note',
    'notes.newNote': 'New Note',
    'notes.saveNote': 'Save Note',
    'notes.noNotes': 'No notes yet. Add your first note to keep track of important information!',
    'notes.edit': 'Edit',
    'notes.preview': 'Preview',
    'notes.placeholder': 'Write your note using markdown...',
    'notes.createFirst': 'Create your first note',
    
    // Categories
    'categories.discoverCategories': 'Découvrir les Catégories',
    'categories.trendingSkills': 'Compétences Tendances',
    'categories.trending': 'Tendance',
    'categories.adopt': 'Adopter',
    'categories.adoptCategory': 'Adopter la Catégorie',
    'categories.skills': 'compétences',
    'categories.skillsIncluded': 'Compétences incluses',
    
    // Skills
    'skills.difficulty.beginner': 'Débutant',
    'skills.difficulty.intermediate': 'Intermédiaire',
    'skills.difficulty.advanced': 'Avancé',
    'skills.difficulty.expert': 'Expert',
    
    // Sessions
    'sessions.title': 'Recent Sessions',
    'sessions.noSessions': 'No sessions recorded yet',
    'sessions.pomodoro': 'Pomodoro',
    'sessions.break': 'Break',
    
    // Achievements
    'achievements.title': 'Achievements',
    'achievements.level': 'Achievement Level',
    'achievements.nextGoal': 'Next Goal: {hours}h',
    'achievements.remaining': '{hours}h remaining ({percent}% complete)',
    'achievements.maxLevel': '🎉 Maximum Level Achieved!',
    'achievements.maxLevelDesc': 'You\'ve reached the highest achievement level',
    'achievements.levels.starter': 'Starter',
    'achievements.levels.beginner': 'Beginner',
    'achievements.levels.intermediate': 'Intermediate',
    'achievements.levels.advanced': 'Advanced',
    'achievements.levels.expert': 'Expert',
    'achievements.levels.master': 'Maître',
    'achievements.unlocked': 'débloqué',
    'achievements.totalTime': 'Temps Total',
    'achievements.tasksDone': 'Tâches Accomplies',
    'achievements.next': 'Suivant',
    'achievements.progress': 'Progression',
    'achievements.yourAchievements': 'Vos Réalisations',
    'achievements.gettingStarted': 'Premiers Pas',
    'achievements.gettingStartedDesc': 'Enregistrez votre première heure',
    'achievements.dedicatedLearner': 'Apprenant Dévoué',
    'achievements.dedicatedLearnerDesc': 'Atteignez 10 heures au total',
    'achievements.skillBuilder': 'Bâtisseur de Compétences',
    'achievements.skillBuilderDesc': 'Atteignez 100 heures',
    'achievements.taskMaster': 'Maître des Tâches',
    'achievements.taskMasterDesc': 'Complétez 50 tâches',
    'achievements.pomodoroPro': 'Pro du Pomodoro',
    'achievements.pomodoroProDesc': 'Complétez 25 sessions pomodoro',
    'achievements.consistencyKing': 'Roi de la Constance',
    'achievements.consistencyKingDesc': 'Enregistrez 100 sessions',
    
    // Profile
    'profile.title': 'Profil',
    'profile.subtitle': 'Gérez votre compte et consultez vos réalisations',
    'profile.personalInfo': 'Informations Personnelles',
    'profile.fullName': 'Nom Complet',
    'profile.nickname': 'Pseudo',
    'profile.dateOfBirth': 'Date de Naissance',
    'profile.security': 'Sécurité',
    'profile.currentPassword': 'Mot de Passe Actuel',
    'profile.newPassword': 'Nouveau Mot de Passe',
    'profile.confirmPassword': 'Confirmer le Nouveau Mot de Passe',
    'profile.changePassword': 'Changer le Mot de Passe',
    'profile.soundNotifications': 'Notifications Sonores',
    'profile.soundDesc': 'Jouer des sons pour les réalisations et les minuteurs',
    'profile.exportData': 'Exporter Toutes les Données',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.profile': 'Profil & Réalisations',
    'settings.security': 'Sécurité',
    'settings.audio': 'Audio',
    'settings.notifications': 'Notifications',
    'settings.data': 'Données',
    'settings.personalInfo': 'Informations Personnelles',
    'settings.fullName': 'Nom Complet',
    'settings.nickname': 'Pseudo',
    'settings.dateOfBirth': 'Date de Naissance',
    'settings.currentPassword': 'Mot de Passe Actuel',
    'settings.newPassword': 'Nouveau Mot de Passe',
    'settings.confirmPassword': 'Confirmer le Nouveau Mot de Passe',
    'settings.changePassword': 'Changer le Mot de Passe',
    'settings.soundNotifications': 'Notifications Sonores',
    'settings.soundDesc': 'Jouer des sons pour les réalisations, pomodoro et tâches accomplies',
    'settings.monthlyReports': 'Rapports Mensuels de Progression',
    'settings.monthlyReportsDesc': 'Recevez des résumés mensuels de votre progression',
    'settings.weeklyReminders': 'Rappels Hebdomadaires des Objectifs',
    'settings.weeklyRemindersDesc': 'Recevez des rappels hebdomadaires de vos objectifs',
    'settings.exportData': 'Exporter Toutes les Données',
    'settings.resetData': 'Réinitialiser Toutes les Données',
    'settings.saveSettings': 'Enregistrer les Paramètres',
    'settings.danger': 'Zone Dangereuse',
    'settings.deleteAccount': 'Supprimer le Compte',
    'settings.deleteAccountWarning': 'Cette action supprimera définitivement votre compte et toutes les données associées. Cette action ne peut pas être annulée.',
    'settings.deleteAccountConfirm': 'Êtes-vous absolument sûr ? Cette action ne peut pas être annulée.',
    'settings.confirmDelete': 'Oui, Supprimer Mon Compte',
    'settings.appearance': 'Apparence',
    'settings.theme': 'Thème',
    'settings.themeDesc': 'Basculer entre le mode clair et sombre',
    'settings.language': 'Langue',
    'settings.languageDesc': 'Choisissez votre langue préférée pour l\'application',
    'settings.onboarding': 'Configuration',
    'settings.onboardingTitle': 'Compléter la Configuration du Profil',
    'settings.onboardingDesc': 'Configurez vos centres d\'intérêt, préférences linguistiques et objectifs quotidiens pour personnaliser votre expérience.',
    'settings.startOnboarding': 'Commencer la Configuration',
    
    // Guide
    'guide.welcome': 'Bienvenue sur TimeXP !',
    'guide.letsGetStarted': 'Commençons votre parcours de productivité',
    'guide.step': 'Étape',
    'guide.whatIsTimeXP': 'Qu\'est-ce que TimeXP ?',
    'guide.timeXPDescription': 'TimeXP est votre compagnon personnel de suivi du temps et de productivité. Suivez votre temps, organisez vos compétences et développez vos talents.',
    'guide.trackTime': 'Suivre le Temps',
    'guide.trackTimeDesc': 'Surveillez comment vous passez votre temps sur différentes activités',
    'guide.organize': 'Organiser',
    'guide.organizeDesc': 'Gardez vos compétences et tâches organisés par catégories',
    'guide.grow': 'Grandir',
    'guide.growDesc': 'Développez de meilleures habitudes et améliorez votre productivité',
    'guide.setupCategories': 'Configurez Vos Catégories',
    'guide.categoriesDescription': 'Basé sur vos centres d\'intérêt, nous créerons des catégories pour organiser vos compétences.',
    'guide.yourInterests': 'Vos Centres d\'Intérêt',
    'guide.createCategoriesFromInterests': 'Créer des Catégories à partir des Intérêts',
    'guide.addSkills': 'Ajoutez Vos Compétences',
    'guide.skillsDescription': 'Ajoutez des compétences spécifiques dans vos catégories pour suivre vos progrès.',
    'guide.addFirstSkill': 'Ajoutez Votre Première Compétence',
    'guide.skipForNow': 'Passer pour l\'instant',
    'guide.skillName': 'Nom de la Compétence',
    'guide.skillNamePlaceholder': 'ex: React, Photoshop, Piano',
    'guide.addSkill': 'Ajouter la Compétence',
    'guide.readyToGo': 'Vous Êtes Prêt !',
    'guide.readyDescription': 'Votre espace de travail TimeXP est configuré et prêt pour votre parcours de productivité.',
    'guide.readyCheck1': 'Votre profil est configuré',
    'guide.readyCheck2': 'Les catégories sont créées à partir de vos intérêts',
    'guide.readyCheck3': 'Vous pouvez commencer à suivre votre temps',
    'guide.startUsing': 'Commencer à Utiliser TimeXP',
    
    // Playlists
    'playlist.title': 'Playlist',
    'playlist.add': 'Ajouter une Playlist',
    'playlist.url': 'URL de la Playlist',
    'playlist.urlPlaceholder': 'Entrez l\'URL d\'une playlist Spotify, YouTube ou Apple Music',
    'playlist.name': 'Nom de la Playlist',
    'playlist.namePlaceholder': 'Entrez un nom pour cette playlist',
    'playlist.save': 'Enregistrer la Playlist',
    'playlist.remove': 'Supprimer la Playlist',
    'playlist.noPlaylist': 'Aucune playlist ajoutée',
    'playlist.addFirst': 'Ajoutez une playlist pour écouter pendant le travail',
    
    // Categories
    'categories.name': 'Nom de la Catégorie',
    'categories.namePlaceholder': 'ex. Développement, Design, Personnel...',
    'categories.color': 'Couleur',
    'categories.icon': 'Icône',
    'categories.create': 'Créer la Catégorie',
    
    // Skills
    'project.name': 'Nom de la Compétence',
    'project.namePlaceholder': 'ex. React, Photoshop, Piano...',
    'project.category': 'Catégorie',
    'project.description': 'Description (optionnel)',
    'project.descriptionPlaceholder': 'Décrivez brièvement cette compétence...',
    'project.create': 'Créer la Compétence',
    'project.enablePomodoro': 'Activer la Technique Pomodoro',
    'project.focusTimeMinutes': 'Temps de Concentration (minutes)',
    'project.breakTimeMinutes': 'Temps de Pause (minutes)',
    
    // Pomodoro
    'pomodoro.title': 'Statistiques Pomodoro',
    'pomodoro.completedSessions': 'Sessions Terminées',
    'pomodoro.focusTime': 'Temps de Concentration',
    'pomodoro.breakTime': 'Temps de Pause',
    'pomodoro.mode': 'Mode Pomodoro',
    
    // Toast
    'toast.hide': 'Masquer le Minuteur',
    'toast.show': 'Afficher le Minuteur',
    'toast.minimize': 'Réduire',
    'toast.expand': 'Agrandir',
    
    // Common
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.add': 'Ajouter',
    'common.create': 'Créer',
    'common.back': 'Retour',
    'common.close': 'Fermer',
    'common.loading': 'Chargement...',
    'common.online': 'En ligne',
    'common.light': 'Clair',
    'common.dark': 'Sombre',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.confirm': 'Confirmer',
    
    // Authentication
    'auth.welcomeBack': 'Bon Retour',
    'auth.signInToContinue': 'Connectez-vous pour continuer sur TimeXP',
    'auth.createAccount': 'Créer un Compte',
    'auth.signUpToGetStarted': 'Inscrivez-vous pour commencer avec TimeXP',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'Entrez votre email',
    'auth.password': 'Mot de passe',
    'auth.passwordPlaceholder': 'Entrez votre mot de passe',
    'auth.confirmPassword': 'Confirmer le Mot de passe',
    'auth.confirmPasswordPlaceholder': 'Confirmez votre mot de passe',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.signIn': 'Se Connecter',
    'auth.signUp': 'S\'inscrire',
    'auth.noAccount': 'Vous n\'avez pas de compte ?',
    'auth.alreadyHaveAccount': 'Vous avez déjà un compte ?',
    'auth.checkYourEmail': 'Vérifiez Votre Email',
    'auth.verificationEmailSent': 'Nous avons envoyé un email de vérification à votre boîte de réception',
    'auth.resetPasswordEmailSent': 'Nous avons envoyé un lien de réinitialisation à votre email',
    'auth.backToSignIn': 'Retour à la Connexion',
    'auth.enterEmailToReset': 'Entrez votre email pour réinitialiser votre mot de passe',
    'auth.sendResetLink': 'Envoyer le Lien de Réinitialisation',
    'auth.passwordsDoNotMatch': 'Les mots de passe ne correspondent pas',
    'auth.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères',
    'auth.chooseNickname': 'Choisissez votre pseudo pour commencer',
    'auth.nickname': 'Pseudo',
    'auth.nicknamePlaceholder': 'Entrez votre pseudo',
    'auth.continue': 'Continuer',
    
    // Upcoming Tasks
    'upcomingTasks.title': 'Tâches à Venir',
    'upcomingTasks.noDeadlines': 'Aucune échéance à venir',
    'upcomingTasks.addDeadlines': 'Ajoutez des échéances à vos tâches pour les voir ici',
    'upcomingTasks.showingNext': 'Affichage des 5 prochaines tâches',
    
    // Onboarding
    'onboarding.welcome': 'Bienvenue sur TimeXP !',
    'onboarding.setupProfile': 'Configurons votre profil pour personnaliser votre expérience',
    'onboarding.step': 'Étape',
    'onboarding.nickname': 'Comment devons-nous vous appeler ?',
    'onboarding.nicknamePlaceholder': 'Entrez votre pseudo',
    'onboarding.nicknameHelp': 'C\'est ainsi que vous apparaîtrez dans l\'application',
    'onboarding.interests': 'Quels sont vos centres d\'intérêt ?',
    'onboarding.interestsHelp': 'Sélectionnez vos domaines d\'intérêt principaux pour personnaliser votre expérience',
    'onboarding.interests.programming': 'Programmation',
    'onboarding.interests.design': 'Design',
    'onboarding.interests.music': 'Musique',
    'onboarding.interests.gaming': 'Jeux vidéo',
    'onboarding.interests.photography': 'Photographie',
    'onboarding.interests.cooking': 'Cuisine',
    'onboarding.interests.travel': 'Voyage',
    'onboarding.interests.reading': 'Lecture',
    'onboarding.preferredLanguage': 'Quelle est votre langue préférée ?',
    'onboarding.dailyGoal': 'Objectif quotidien (heures)',
    'onboarding.dailyGoalHelp': 'Combien d\'heures voulez-vous consacrer à vos compétences chaque jour ?',
    'onboarding.complete': 'Terminer la configuration',
    
    // Admin
    'admin.skills.title': 'Gestion des Compétences',
    'admin.skills.subtitle': 'Gérer les compétences disponibles et suivre leur popularité',
    'admin.skills.addSkill': 'Ajouter une Compétence',
    'admin.skills.editSkill': 'Modifier la Compétence',
    'admin.skills.totalSkills': 'Total des Compétences',
    'admin.skills.activeSkills': 'Compétences Actives',
    'admin.skills.totalUsers': 'Total des Utilisateurs',
    'admin.skills.skill': 'Compétence',
    'admin.skills.category': 'Catégorie',
    'admin.skills.popularity': 'Popularité',
    'admin.skills.status': 'Statut',
    'admin.skills.actions': 'Actions',
    'admin.skills.active': 'Active',
    'admin.skills.inactive': 'Inactive',
    'admin.skills.name': 'Nom',
    'admin.skills.description': 'Description',
    'admin.skills.color': 'Couleur',
    'admin.skills.categories.programming': 'Programmation',
    'admin.skills.categories.design': 'Design',
    'admin.skills.categories.music': 'Musique',
    'admin.skills.categories.gaming': 'Jeux vidéo',
    'admin.skills.categories.photography': 'Photographie',
    'admin.skills.categories.cooking': 'Cuisine',
    'admin.skills.categories.travel': 'Voyage',
    'admin.skills.categories.reading': 'Lecture',
    'admin.skills.categories.fitness': 'Fitness',
    'admin.skills.categories.art': 'Art',
    'admin.skills.categories.business': 'Business',
    'admin.skills.categories.education': 'Éducation',
    
    // Admin Panel - New Features
    'admin.overview': 'Vue d\'ensemble',
    'admin.categories': 'Catégories',
    'admin.users': 'Utilisateurs',
    'admin.articles': 'Articles',
    'admin.analytics': 'Analyses',
    'admin.recentUsers': 'Utilisateurs Récents',
    'admin.trendingSkills': 'Compétences Tendances',
    'admin.defaultCategories': 'Gestion des Catégories par Défaut',
    'admin.manageDefaultCategories': 'Gérer les catégories par défaut et leurs compétences',
    'admin.userManagement': 'Gestion des Utilisateurs',
    'admin.manageUsers': 'Gérer les utilisateurs et leurs accès',
    'admin.articleManagement': 'Gestion des Articles',
    'admin.createManageArticles': 'Créer et gérer des articles pour les utilisateurs',
    'admin.createArticle': 'Créer un Article',
    'admin.advancedAnalytics': 'Analyses Avancées',
    'admin.userGrowth': 'Croissance des Utilisateurs',
    'admin.skillPopularity': 'Popularité des Compétences',
    'admin.timeTrackingAnalytics': 'Analyses du Suivi du Temps',
    'admin.totalHoursTracked': 'Total des Heures Suivies',
    'admin.averageSessionLength': 'Durée Moyenne des Sessions',
    'admin.categoryDistribution': 'Distribution des Catégories',
    'admin.chartComingSoon': 'Graphique à venir...',
    'admin.loadingAdminData': 'Chargement des données d\'administration...',
    'admin.noNickname': 'Aucun pseudo',
    'admin.active': 'Actif',
    'admin.inactive': 'Inactif',
    'admin.joined': 'Inscrit le',
    'admin.actions': 'Actions',
    'admin.edit': 'Modifier',
    'admin.delete': 'Supprimer',
    'admin.trending': 'Tendance',
    'admin.skills': 'compétences',
    'admin.hours': 'heures',
    'admin.minutes': 'minutes'
  },
  es: {
    // App
    'app.title': 'TimeXP',
    'app.subtitle': 'Seguimiento del Desarrollo de Habilidades',
    'app.greeting.morning': 'Buenos días',
    'app.greeting.afternoon': 'Buenas tardes', 
    'app.greeting.evening': 'Buenas noches',
    'app.motivation.1': '¿En qué trabajamos hoy?',
    'app.motivation.2': '¿Listo para progresar?',
    'app.motivation.3': '¡Es hora de alcanzar tus metas!',
    'app.motivation.4': '¡Construyamos algo increíble!',
    'app.motivation.5': '¡Tu próximo avance te espera!',
    
    // Navigation
    'nav.dashboard': 'Panel',
    'nav.pinned': 'Fijados',
    'nav.categories': 'Categorías',
    'nav.settings': 'Ajustes',
    'nav.logout': 'Cerrar sesión',
    'nav.login': 'Iniciar sesión',
    'nav.profile': 'Perfil',
    
    // Dashboard
    'dashboard.totalTime': 'Tiempo Total Registrado',
    'dashboard.activeProjects': 'Proyectos Activos',
    'dashboard.tasksCompleted': 'Tareas Completadas',
    'dashboard.newCategory': 'Nueva Categoría',
    'dashboard.noCategories': 'No hay categorías creadas aún',
    'dashboard.createFirstCategory': 'Crea tu primera categoría',
    
    // Projects
    'projects.new': 'Nuevo Proyecto',
    'projects.pinned': 'Proyectos Fijados',
    'projects.noPinned': 'No hay proyectos fijados aún',
    'projects.noProjects': 'No hay proyectos creados aún',
    'projects.createFirst': 'Crea tu primer proyecto',
    'projects.totalTime': 'Tiempo Total',
    'projects.tasks': 'Tareas',
    
    // Timer
    'timer.start': 'Iniciar',
    'timer.pause': 'Pausar',
    'timer.resume': 'Reanudar',
    'timer.stop': 'Detener',
    'timer.currentSession': 'Sesión actual',
    'timer.addSession': 'Agregar Sesión',
    'timer.addManualSession': 'Agregar Sesión Manual',
    'timer.focusTime': 'Tiempo de Enfoque',
    'timer.breakTime': 'Tiempo de Descanso',
    'timer.totalDuration': 'Duración Total',
    'timer.startTime': 'Hora de Inicio',
    'timer.description': 'Descripción',
    'timer.descriptionPlaceholder': '¿En qué trabajaste durante esta sesión?',
    'timer.hours': 'Horas',
    'timer.minutes': 'Minutos',
    'timer.date': 'Fecha',
    
    // Tasks
    'tasks.title': 'Tareas',
    'tasks.add': 'Agregar',
    'tasks.addTask': 'Agregar Tarea',
    'tasks.noTasks': '¡No hay tareas creadas aún. Agrega tu primera tarea para comenzar!',
    'tasks.deadline': 'Fecha límite (opcional)',
    'tasks.priority': 'Prioridad',
    'tasks.priority.low': 'Baja',
    'tasks.priority.medium': 'Media',
    'tasks.priority.high': 'Alta',
    'tasks.dueToday': 'Vence hoy',
    'tasks.dueTomorrow': 'Vence mañana',
    'tasks.dueInDays': 'Vence en {days} días',
    'tasks.overdue': '{days} días de retraso',
    'tasks.taskName': 'Nombre de la tarea...',
    'tasks.lowPriority': 'prioridad baja',
    'tasks.mediumPriority': 'prioridad media',
    'tasks.highPriority': 'prioridad alta',
    
    // Notes
    'notes.title': 'Notas',
    'notes.add': 'Agregar Nota',
    'notes.addNote': 'Agregar Nota',
    'notes.newNote': 'Nueva Nota',
    'notes.saveNote': 'Guardar Nota',
    'notes.noNotes': '¡No hay notas aún. Agrega tu primera nota para mantener un registro de información importante!',
    'notes.edit': 'Editar',
    'notes.preview': 'Vista previa',
    'notes.placeholder': 'Escribe tu nota usando markdown...',
    'notes.createFirst': 'Crea tu primera nota',
    
    // Sessions
    'sessions.title': 'Sesiones Recientes',
    'sessions.noSessions': 'No hay sesiones registradas aún',
    'sessions.pomodoro': 'Pomodoro',
    'sessions.break': 'Descanso',
    
    // Achievements
    'achievements.title': 'Logros',
    'achievements.level': 'Nivel de Logro',
    'achievements.nextGoal': 'Siguiente Meta: {hours}h',
    'achievements.remaining': '{hours}h restantes ({percent}% completado)',
    'achievements.maxLevel': '🎉 ¡Nivel Máximo Alcanzado!',
    'achievements.maxLevelDesc': 'Has alcanzado el nivel más alto de logros',
    'achievements.levels.starter': 'Principiante',
    'achievements.levels.beginner': 'Novato',
    'achievements.levels.intermediate': 'Intermedio',
    'achievements.levels.advanced': 'Avanzado',
    'achievements.levels.expert': 'Experto',
    'achievements.levels.master': 'Maestro',
    'achievements.unlocked': 'desbloqueado',
    'achievements.totalTime': 'Tiempo Total',
    'achievements.tasksDone': 'Tareas Completadas',
    'achievements.next': 'Siguiente',
    'achievements.progress': 'Progreso',
    'achievements.yourAchievements': 'Tus Logros',
    'achievements.gettingStarted': 'Comenzando',
    'achievements.gettingStartedDesc': 'Registra tu primera hora',
    'achievements.dedicatedLearner': 'Aprendiz Dedicado',
    'achievements.dedicatedLearnerDesc': 'Alcanza 10 horas en total',
    'achievements.skillBuilder': 'Constructor de Habilidades',
    'achievements.skillBuilderDesc': 'Logra 100 horas',
    'achievements.taskMaster': 'Maestro de Tareas',
    'achievements.taskMasterDesc': 'Completa 50 tareas',
    'achievements.pomodoroPro': 'Pro del Pomodoro',
    'achievements.pomodoroProDesc': 'Completa 25 sesiones pomodoro',
    'achievements.consistencyKing': 'Rey de la Consistencia',
    'achievements.consistencyKingDesc': 'Registra 100 sesiones',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.subtitle': 'Administra tu cuenta y ve tus logros',
    'profile.personalInfo': 'Información Personal',
    'profile.fullName': 'Nombre Completo',
    'profile.nickname': 'Apodo',
    'profile.dateOfBirth': 'Fecha de Nacimiento',
    'profile.security': 'Seguridad',
    'profile.currentPassword': 'Contraseña Actual',
    'profile.newPassword': 'Nueva Contraseña',
    'profile.confirmPassword': 'Confirmar Nueva Contraseña',
    'profile.changePassword': 'Cambiar Contraseña',
    'profile.soundNotifications': 'Notificaciones de Sonido',
    'profile.soundDesc': 'Reproducir sonidos para logros y temporizadores',
    'profile.exportData': 'Exportar Todos los Datos',
    
    // Settings
    'settings.title': 'Ajustes',
    'settings.profile': 'Perfil y Logros',
    'settings.security': 'Seguridad',
    'settings.audio': 'Audio',
    'settings.notifications': 'Notificaciones',
    'settings.data': 'Datos',
    'settings.personalInfo': 'Información Personal',
    'settings.fullName': 'Nombre Completo',
    'settings.nickname': 'Apodo',
    'settings.dateOfBirth': 'Fecha de Nacimiento',
    'settings.currentPassword': 'Contraseña Actual',
    'settings.newPassword': 'Nueva Contraseña',
    'settings.confirmPassword': 'Confirmar Nueva Contraseña',
    'settings.changePassword': 'Cambiar Contraseña',
    'settings.soundNotifications': 'Notificaciones de Sonido',
    'settings.soundDesc': 'Reproducir sonidos para logros, pomodoro y tareas completadas',
    'settings.monthlyReports': 'Informes Mensuales de Progreso',
    'settings.monthlyReportsDesc': 'Recibe resúmenes mensuales de tu progreso',
    'settings.weeklyReminders': 'Recordatorios Semanales de Metas',
    'settings.weeklyRemindersDesc': 'Recibe recordatorios semanales sobre tus metas',
    'settings.exportData': 'Exportar Todos los Datos',
    'settings.resetData': 'Restablecer Todos los Datos',
    'settings.saveSettings': 'Guardar Ajustes',
    
    // Playlists
    'playlist.title': 'Lista de Reproducción',
    'playlist.add': 'Agregar Lista',
    'playlist.url': 'URL de la Lista',
    'playlist.urlPlaceholder': 'Ingresa URL de lista de Spotify, YouTube o Apple Music',
    'playlist.name': 'Nombre de la Lista',
    'playlist.namePlaceholder': 'Ingresa un nombre para esta lista',
    'playlist.save': 'Guardar Lista',
    'playlist.remove': 'Eliminar Lista',
    'playlist.noPlaylist': 'No hay listas agregadas aún',
    'playlist.addFirst': 'Agrega una lista para escuchar mientras trabajas',
    
    // Categories
    'categories.name': 'Nombre de Categoría',
    'categories.namePlaceholder': 'ej. Desarrollo, Diseño, Personal...',
    'categories.color': 'Color',
    'categories.icon': 'Icono',
    'categories.create': 'Crear Categoría',
    
    // Projects
    'project.name': 'Nombre del Proyecto',
    'project.namePlaceholder': 'ej. Sitio Web del Cliente, App Móvil...',
    'project.category': 'Categoría',
    'project.description': 'Descripción (opcional)',
    'project.descriptionPlaceholder': 'Describe brevemente este proyecto...',
    'project.create': 'Crear Proyecto',
    'project.enablePomodoro': 'Habilitar Técnica Pomodoro',
    'project.focusTimeMinutes': 'Tiempo de Enfoque (minutos)',
    'project.breakTimeMinutes': 'Tiempo de Descanso (minutos)',
    
    // Pomodoro
    'pomodoro.title': 'Estadísticas Pomodoro',
    'pomodoro.completedSessions': 'Sesiones Completadas',
    'pomodoro.focusTime': 'Tiempo de Enfoque',
    'pomodoro.breakTime': 'Tiempo de Descanso',
    'pomodoro.mode': 'Modo Pomodoro',
    
    // Toast
    'toast.hide': 'Ocultar Temporizador',
    'toast.show': 'Mostrar Temporizador',
    'toast.minimize': 'Minimizar',
    'toast.expand': 'Expandir',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Agregar',
    'common.create': 'Crear',
    'common.back': 'Atrás',
    'common.close': 'Cerrar',
    'common.loading': 'Cargando...',
    'common.online': 'En línea',
    'common.light': 'Claro',
    'common.dark': 'Oscuro',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.confirm': 'Confirmar',
    
    // Authentication
    'auth.welcomeBack': 'Bienvenido de Nuevo',
    'auth.signInToContinue': 'Inicia sesión para continuar en TimeXP',
    'auth.createAccount': 'Crear Cuenta',
    'auth.signUpToGetStarted': 'Regístrate para comenzar con TimeXP',
    'auth.email': 'Correo electrónico',
    'auth.emailPlaceholder': 'Ingresa tu correo electrónico',
    'auth.password': 'Contraseña',
    'auth.passwordPlaceholder': 'Ingresa tu contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.confirmPasswordPlaceholder': 'Confirma tu contraseña',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.signIn': 'Iniciar Sesión',
    'auth.signUp': 'Registrarse',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'auth.checkYourEmail': 'Revisa Tu Correo',
    'auth.verificationEmailSent': 'Hemos enviado un correo de verificación a tu bandeja de entrada',
    'auth.resetPasswordEmailSent': 'Hemos enviado un enlace de restablecimiento a tu correo',
    'auth.backToSignIn': 'Volver a Iniciar Sesión',
    'auth.enterEmailToReset': 'Ingresa tu correo para restablecer tu contraseña',
    'auth.sendResetLink': 'Enviar Enlace de Restablecimiento',
    'auth.passwordsDoNotMatch': 'Las contraseñas no coinciden',
    'auth.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres'
  },
  sv: {
    // App
    'app.title': 'TimeXP',
    'app.subtitle': 'Färdighetsutvecklingsspårare',
    'app.greeting.morning': 'God morgon',
    'app.greeting.afternoon': 'God eftermiddag',
    'app.greeting.evening': 'God kväll',
    'app.motivation.1': 'Vad jobbar vi med idag?',
    'app.motivation.2': 'Redo att göra framsteg?',
    'app.motivation.3': 'Dags att nå dina mål!',
    'app.motivation.4': 'Låt oss bygga något fantastiskt!',
    'app.motivation.5': 'Ditt nästa genombrott väntar!',
    
    // Navigation
    'nav.dashboard': 'Instrumentpanel',
    'nav.pinned': 'Fästa',
    'nav.categories': 'Kategorier',
    'nav.settings': 'Inställningar',
    'nav.logout': 'Logga ut',
    'nav.login': 'Logga in',
    'nav.profile': 'Profil',
    
    // Dashboard
    'dashboard.totalTime': 'Total Loggad Tid',
    'dashboard.activeProjects': 'Aktiva Projekt',
    'dashboard.tasksCompleted': 'Avklarade Uppgifter',
    'dashboard.newCategory': 'Ny Kategori',
    'dashboard.noCategories': 'Inga kategorier skapade än',
    'dashboard.createFirstCategory': 'Skapa din första kategori',
    
    // Projects
    'projects.new': 'Nytt Projekt',
    'projects.pinned': 'Fästa Projekt',
    'projects.noPinned': 'Inga fästa projekt än',
    'projects.noProjects': 'Inga projekt skapade än',
    'projects.createFirst': 'Skapa ditt första projekt',
    'projects.totalTime': 'Total Tid',
    'projects.tasks': 'Uppgifter',
    
    // Timer
    'timer.start': 'Starta',
    'timer.pause': 'Pausa',
    'timer.resume': 'Återuppta',
    'timer.stop': 'Stoppa',
    'timer.currentSession': 'Aktuell session',
    'timer.addSession': 'Lägg till Session',
    'timer.addManualSession': 'Lägg till Manuell Session',
    'timer.focusTime': 'Fokustid',
    'timer.breakTime': 'Paustid',
    'timer.totalDuration': 'Total Varaktighet',
    'timer.startTime': 'Starttid',
    'timer.description': 'Beskrivning',
    'timer.descriptionPlaceholder': 'Vad jobbade du med under denna session?',
    'timer.hours': 'Timmar',
    'timer.minutes': 'Minuter',
    'timer.date': 'Datum',
    
    // Tasks
    'tasks.title': 'Uppgifter',
    'tasks.add': 'Lägg till',
    'tasks.addTask': 'Lägg till Uppgift',
    'tasks.noTasks': 'Inga uppgifter skapade än. Lägg till din första uppgift för att komma igång!',
    'tasks.deadline': 'Deadline (valfritt)',
    'tasks.priority': 'Prioritet',
    'tasks.priority.low': 'Låg',
    'tasks.priority.medium': 'Medel',
    'tasks.priority.high': 'Hög',
    'tasks.dueToday': 'Förfaller idag',
    'tasks.dueTomorrow': 'Förfaller imorgon',
    'tasks.dueInDays': 'Förfaller om {days} dagar',
    'tasks.overdue': '{days} dagar försenad',
    'tasks.taskName': 'Uppgiftsnamn...',
    'tasks.lowPriority': 'låg prioritet',
    'tasks.mediumPriority': 'medel prioritet',
    'tasks.highPriority': 'hög prioritet',
    
    // Notes
    'notes.title': 'Anteckningar',
    'notes.add': 'Lägg till Anteckning',
    'notes.addNote': 'Lägg till Anteckning',
    'notes.newNote': 'Ny Anteckning',
    'notes.saveNote': 'Spara Anteckning',
    'notes.noNotes': 'Inga anteckningar än. Lägg till din första anteckning för att hålla koll på viktig information!',
    'notes.edit': 'Redigera',
    'notes.preview': 'Förhandsgranska',
    'notes.placeholder': 'Skriv din anteckning med markdown...',
    'notes.createFirst': 'Skapa din första anteckning',
    
    // Sessions
    'sessions.title': 'Senaste Sessioner',
    'sessions.noSessions': 'Inga sessioner registrerade än',
    'sessions.pomodoro': 'Pomodoro',
    'sessions.break': 'Paus',
    
    // Achievements
    'achievements.title': 'Prestationer',
    'achievements.level': 'Prestationsnivå',
    'achievements.nextGoal': 'Nästa Mål: {hours}h',
    'achievements.remaining': '{hours}h kvar ({percent}% klart)',
    'achievements.maxLevel': '🎉 Maximal Nivå Uppnådd!',
    'achievements.maxLevelDesc': 'Du har nått den högsta prestationsnivån',
    'achievements.levels.starter': 'Nybörjare',
    'achievements.levels.beginner': 'Början',
    'achievements.levels.intermediate': 'Medel',
    'achievements.levels.advanced': 'Avancerad',
    'achievements.levels.expert': 'Expert',
    'achievements.levels.master': 'Mästare',
    'achievements.unlocked': 'upplåst',
    'achievements.totalTime': 'Total Tid',
    'achievements.tasksDone': 'Avklarade Uppgifter',
    'achievements.next': 'Nästa',
    'achievements.progress': 'Framsteg',
    'achievements.yourAchievements': 'Dina Prestationer',
    'achievements.gettingStarted': 'Komma Igång',
    'achievements.gettingStartedDesc': 'Logga din första timme',
    'achievements.dedicatedLearner': 'Dedikerad Inlärare',
    'achievements.dedicatedLearnerDesc': 'Nå 10 timmar totalt',
    'achievements.skillBuilder': 'Färdighetsbyggare',
    'achievements.skillBuilderDesc': 'Uppnå 100 timmar',
    'achievements.taskMaster': 'Uppgiftsmästare',
    'achievements.taskMasterDesc': 'Slutför 50 uppgifter',
    'achievements.pomodoroPro': 'Pomodoro Pro',
    'achievements.pomodoroProDesc': 'Slutför 25 pomodoro-sessioner',
    'achievements.consistencyKing': 'Konsistenskung',
    'achievements.consistencyKingDesc': 'Logga 100 sessioner',
    
    // Profile
    'profile.title': 'Profil',
    'profile.subtitle': 'Hantera ditt konto och visa prestationer',
    'profile.personalInfo': 'Personlig Information',
    'profile.fullName': 'Fullständigt Namn',
    'profile.nickname': 'Smeknamn',
    'profile.dateOfBirth': 'Födelsedatum',
    'profile.security': 'Säkerhet',
    'profile.currentPassword': 'Nuvarande Lösenord',
    'profile.newPassword': 'Nytt Lösenord',
    'profile.confirmPassword': 'Bekräfta Nytt Lösenord',
    'profile.changePassword': 'Ändra Lösenord',
    'profile.soundNotifications': 'Ljudaviseringar',
    'profile.soundDesc': 'Spela ljud för prestationer och timers',
    'profile.exportData': 'Exportera All Data',
    
    // Settings
    'settings.title': 'Inställningar',
    'settings.profile': 'Profil & Prestationer',
    'settings.security': 'Säkerhet',
    'settings.audio': 'Ljud',
    'settings.notifications': 'Aviseringar',
    'settings.data': 'Data',
    'settings.personalInfo': 'Personlig Information',
    'settings.fullName': 'Fullständigt Namn',
    'settings.nickname': 'Smeknamn',
    'settings.dateOfBirth': 'Födelsedatum',
    'settings.currentPassword': 'Nuvarande Lösenord',
    'settings.newPassword': 'Nytt Lösenord',
    'settings.confirmPassword': 'Bekräfta Nytt Lösenord',
    'settings.changePassword': 'Ändra Lösenord',
    'settings.soundNotifications': 'Ljudaviseringar',
    'settings.soundDesc': 'Spela ljud för prestationer, pomodoro och uppgiftsavslut',
    'settings.monthlyReports': 'Månadsrapporter om Framsteg',
    'settings.monthlyReportsDesc': 'Få månatliga sammanfattningar av dina framsteg',
    'settings.weeklyReminders': 'Veckovisa Målpåminnelser',
    'settings.weeklyRemindersDesc': 'Få veckovisa påminnelser om dina mål',
    'settings.exportData': 'Exportera All Data',
    'settings.resetData': 'Återställ All Data',
    'settings.saveSettings': 'Spara Inställningar',
    
    // Playlists
    'playlist.title': 'Spellista',
    'playlist.add': 'Lägg till Spellista',
    'playlist.url': 'Spellista URL',
    'playlist.urlPlaceholder': 'Ange Spotify, YouTube eller Apple Music spellista URL',
    'playlist.name': 'Spellistans Namn',
    'playlist.namePlaceholder': 'Ange ett namn för denna spellista',
    'playlist.save': 'Spara Spellista',
    'playlist.remove': 'Ta bort Spellista',
    'playlist.noPlaylist': 'Ingen spellista tillagd än',
    'playlist.addFirst': 'Lägg till en spellista att lyssna på medan du arbetar',
    
    // Categories
    'categories.name': 'Kategorinamn',
    'categories.namePlaceholder': 't.ex. Utveckling, Design, Personligt...',
    'categories.color': 'Färg',
    'categories.icon': 'Ikon',
    'categories.create': 'Skapa Kategori',
    
    // Projects
    'project.name': 'Projektnamn',
    'project.namePlaceholder': 't.ex. Kundwebbplats, Mobilapp...',
    'project.category': 'Kategori',
    'project.description': 'Beskrivning (valfritt)',
    'project.descriptionPlaceholder': 'Beskriv kort detta projekt...',
    'project.create': 'Skapa Projekt',
    'project.enablePomodoro': 'Aktivera Pomodoro-teknik',
    'project.focusTimeMinutes': 'Fokustid (minuter)',
    'project.breakTimeMinutes': 'Paustid (minuter)',
    
    // Pomodoro
    'pomodoro.title': 'Pomodoro Statistik',
    'pomodoro.completedSessions': 'Avslutade Sessioner',
    'pomodoro.focusTime': 'Fokustid',
    'pomodoro.breakTime': 'Paustid',
    'pomodoro.mode': 'Pomodoro-läge',
    
    // Toast
    'toast.hide': 'Dölj Timer',
    'toast.show': 'Visa Timer',
    'toast.minimize': 'Minimera',
    'toast.expand': 'Expandera',
    
    // Common
    'common.save': 'Spara',
    'common.cancel': 'Avbryt',
    'common.delete': 'Ta bort',
    'common.edit': 'Redigera',
    'common.add': 'Lägg till',
    'common.create': 'Skapa',
    'common.back': 'Tillbaka',
    'common.close': 'Stäng',
    'common.loading': 'Laddar...',
    'common.online': 'Online',
    'common.light': 'Ljust',
    'common.dark': 'Mörkt',
    'common.yes': 'Ja',
    'common.no': 'Nej',
    'common.confirm': 'Bekräfta',
    
    // Authentication
    'auth.welcomeBack': 'Välkommen Tillbaka',
    'auth.signInToContinue': 'Logga in för att fortsätta till TimeXP',
    'auth.createAccount': 'Skapa Konto',
    'auth.signUpToGetStarted': 'Registrera dig för att komma igång med TimeXP',
    'auth.email': 'E-post',
    'auth.emailPlaceholder': 'Ange din e-post',
    'auth.password': 'Lösenord',
    'auth.passwordPlaceholder': 'Ange ditt lösenord',
    'auth.confirmPassword': 'Bekräfta Lösenord',
    'auth.confirmPasswordPlaceholder': 'Bekräfta ditt lösenord',
    'auth.forgotPassword': 'Glömt Lösenord?',
    'auth.signIn': 'Logga In',
    'auth.signUp': 'Registrera',
    'auth.noAccount': 'Har du inget konto?',
    'auth.alreadyHaveAccount': 'Har du redan ett konto?',
    'auth.checkYourEmail': 'Kolla Din E-post',
    'auth.verificationEmailSent': 'Vi har skickat ett verifieringsmail till din inkorg',
    'auth.resetPasswordEmailSent': 'Vi har skickat en återställningslänk till din e-post',
    'auth.backToSignIn': 'Tillbaka till Inloggning',
    'auth.enterEmailToReset': 'Ange din e-post för att återställa ditt lösenord',
    'auth.sendResetLink': 'Skicka Återställningslänk',
    'auth.passwordsDoNotMatch': 'Lösenorden matchar inte',
    'auth.passwordTooShort': 'Lösenordet måste vara minst 6 tecken långt'
  },

};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    if (saved && Object.keys(translations).includes(saved)) {
      return saved as Language;
    }
    // Auto-detect browser language
    const browserLang = navigator.language.split('-')[0];
    const detectedLang = Object.keys(translations).includes(browserLang) ? browserLang as Language : 'en';
    return detectedLang;
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    const currentTranslations = translations[language as keyof typeof translations];
    
    // Direct lookup in the current language translations
    const translation = (currentTranslations as Record<string, string>)?.[key];
    
    // If translation found in current language, return it
    if (translation) {
      return translation;
    }
    
    // Fallback to English if translation not found in current language
    if (language !== 'en') {
      const englishTranslations = translations.en as Record<string, string>;
      const englishTranslation = englishTranslations[key];
      if (englishTranslation) {
        return englishTranslation;
      }
    }
    
    // If no translation found in any language, return the key
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}